### PR TITLE
Update unit tests

### PR DESCRIPTION
**Pull request by tzussman**
- Add more unit tests - code coverage went from 48% to 72%
- Add HydroBasins test data along with input and output test data
- Add github workflow for testing - uses the matrix strategy and needs to be tested (My windows command line skills are a bit shaky)
- We're still dealing with the weird GEE behavior where it returns diff values on diff runs for same input. I implemented fuzzy equals on the results dictionary to work around this

### CODE REVIEW

**Comment by jsta** [comment]
I think we need `source activate rabpro` not `conda activate rabpro` in the ghactions script

**Comment by jonschwenk** [comment]
Looks like something funky's up with the 3.7 and 3.9 builds. Likely unable to solve those environments for whatever reason. Could be RivGraph's fault, although I think it's ok for 3.9...

**Comment by tzussman** [comment]
Yeah it's RivGraph's fault - it requires Python 3.8 to be used, so nothing else works

**Comment by tzussman** [comment]
Fixed a number of issues with conda, pip, caching, paths, and directory structure. The only remaining issue (for now) is the lack of a tif file in MERIT_ELEV_HP. @jonschwenk the original zip file you sent me didn't have an elv.tif file, so if you could send me the corresponding tile that'd be great!

**Comment by jonschwenk** [comment]
Weird, I have an elev.tif file in the folder but I must've not included it. Will plop it in slack.

**Pull request merged**
